import { layoutArchitectureNodes } from '@/lib/city-layout';
import type { ArchitectureGraph } from '@/types/architecture';

export const mockArchitectureGraph: ArchitectureGraph = {
  repoUrl: 'https://github.com/vercel/next.js',
  repoName: 'Demo City',
  generatedAt: new Date().toISOString(),
  stats: {
    totalFiles: 28,
    totalNodes: 7,
    totalEdges: 8,
  },
  nodes: layoutArchitectureNodes([
    {
      id: 'api:api',
      label: 'API Grid',
      type: 'api',
      buildingKind: 'tower',
      path: 'app/api',
      fileCount: 6,
      dependencyCount: 14,
      routeCount: 6,
      queryCount: 0,
      size: [16, 64, 16],
      files: ['app/api/analyze/route.ts', 'app/api/auth/route.ts'],
    },
    {
      id: 'database:data',
      label: 'Data Vault',
      type: 'database',
      buildingKind: 'vault',
      path: 'src/lib/db',
      fileCount: 3,
      dependencyCount: 8,
      routeCount: 0,
      queryCount: 12,
      size: [32, 42, 32],
      files: ['src/lib/db/client.ts', 'src/lib/db/queries.ts'],
    },
    {
      id: 'authentication:auth',
      label: 'Auth Gate',
      type: 'authentication',
      buildingKind: 'gate',
      path: 'src/auth',
      fileCount: 4,
      dependencyCount: 10,
      routeCount: 0,
      queryCount: 0,
      size: [13, 58, 8],
      files: ['src/auth/index.ts', 'src/auth/session.ts'],
    },
    {
      id: 'middleware:middleware',
      label: 'Security Wall',
      type: 'middleware',
      buildingKind: 'security-wall',
      path: 'src/middleware',
      fileCount: 2,
      dependencyCount: 5,
      routeCount: 0,
      queryCount: 0,
      size: [38, 26, 7],
      files: ['src/middleware.ts'],
    },
    {
      id: 'component:components',
      label: 'Component District',
      type: 'component',
      buildingKind: 'block',
      path: 'src/components',
      fileCount: 9,
      dependencyCount: 22,
      routeCount: 0,
      queryCount: 0,
      size: [22, 48, 22],
      files: ['src/components/ui/panel.tsx', 'src/components/graph-card.tsx'],
    },
    {
      id: 'utility:utils',
      label: 'Utility Workshop',
      type: 'utility',
      buildingKind: 'workshop',
      path: 'src/lib/utils',
      fileCount: 4,
      dependencyCount: 7,
      routeCount: 0,
      queryCount: 0,
      size: [12, 28, 12],
      files: ['src/lib/format.ts', 'src/lib/color.ts'],
    },
    {
      id: 'logger:observability',
      label: 'Surveillance Hub',
      type: 'logger',
      buildingKind: 'surveillance-hub',
      path: 'src/lib/logger',
      fileCount: 2,
      dependencyCount: 6,
      routeCount: 0,
      queryCount: 0,
      size: [16, 42, 16],
      files: ['src/lib/logger.ts'],
    },
  ]),
  edges: [
    { source: 'api:api', target: 'database:data', weight: 4 },
    { source: 'api:api', target: 'authentication:auth', weight: 3 },
    { source: 'api:api', target: 'utility:utils', weight: 2 },
    { source: 'middleware:middleware', target: 'authentication:auth', weight: 2 },
    { source: 'component:components', target: 'api:api', weight: 3 },
    { source: 'component:components', target: 'utility:utils', weight: 4 },
    { source: 'authentication:auth', target: 'database:data', weight: 2 },
    { source: 'logger:observability', target: 'api:api', weight: 1 },
  ],
};
